### ISSUE TITLE
some issues with the exercises

### ISSUE THREAD

**Issue by SYAN83** [tristandres/test#1]
# List comprehension ifs
try to combine conditions with logical operators, i.e., 
```
[x for x in range(100) if x % 2 == 0 and x % 6 == 0]
```
also, if a number is divisible by 6, it must be divisible by 2, so x % 2 == 0 is redundant.

# primes numbers between two numbers
The result seems not correct (1 is not a prime number, 5 is missing from the result), here's my solution
```
def prime(n):
    if n < 2:
        return list()
    elif n < 4:
        return [2] if n < 3 else [2, 3]
    else:
        res = [2, 3]
        for i in range(5, n, 2):
            for j in res:
                if i % j == 0:
                    break
            else:
                res.append(i)
        return res
```

# Create a function to solve the Fibonacci sequence
Time Complexity of recursion when solving Fibonacci is exponential.Try implementation with iterative way or use lru cache, for example

```
from functools import lru_cache

@lru_cache()
def fibo(n):
    if n == 1 or n == 2:
        return 1
    else:
        return fibo(n - 1) + fibo(n - 2)
```

see https://www.geeksforgeeks.org/program-for-nth-fibonacci-number/

**Comment by tristandres** [comment]
All changes have been made!
